### ISSUE TITLE
Key is not removed from session

### ISSUE THREAD

**Issue by shining-mind** [fletcherist/yandex-dialogs-sdk-lowdb#1]
It seems that this problem occurs, because 'session.' prefix is missing.

https://github.com/fletcherist/yandex-dialogs-sdk-lowdb/blob/3044fdfefde0cbac93c04371703af2c6cbdaf619/src/lowdbSession.ts#L22

**Comment by fletcherist** [comment]
@shining-mind  thanks. i'll fix this right now

**Comment by shining-mind** [comment]
Fixed: 15cfece9dd48eee21ab6de6f4e66cecee1dce07f
